### ISSUE TITLE
Remove `prettier` from dependencies

### ISSUE THREAD

**Issue by rtritto** [ijsto/eslint-config#14]
`prettier` dependency is a peerDependencies of `eslint-plugin-prettier`.
`eslint-plugin-prettier` plugin can be disabled changing _.eslintrc.yml_ file as follow:
```yml
rules:
  prettier/prettier: 0
```
So `prettier` dependency is useless in dependencies of _package.json_ file and, to prevent its install, it should be removed from dependencies and become optional.

Changes in _package.json_ file:
- remove `prettier` dependency from _dependencies_ (run `yarn remove prettier`)
- add manually (I don't know if there are yarn commands to update/create these fields):
```json
  "peerDependencies": {
    ...
    "prettier": ">= 2.x.x" // OR exact version; it should be equal/compatible/maintained with peerDependency.prettier version value of eslint-plugin-prettier
  },
  "peerDependenciesMeta": {
    "prettier": {
      "optional": true
    }
  }
```

PS: these changes must be tested

**Comment by ScottAgirs** [comment]
Hello @rtritto thank you for opening the issue. Would you be open to submitting a PR for this?

**Comment by rtritto** [comment]
@ScottAgirs PR opened

**Comment by ScottAgirs** [comment]
09e7cce1e74d2a05075d757c2944df7bd012abb5

**Comment by ScottAgirs** [comment]
https://github.com/ijsto/eslint-config/releases/tag/v4.3.3
