### ISSUE TITLE
VSCode Extensions

### ISSUE THREAD

**Issue by cjboco** [ijsto/eslint-config#3]
I know it seems silly, but you might want to add in the instructions that you need to have these extensions installed in VSCode:

ESLint (dbaeumer.vscode-eslint) 
Prettier - Code formatter (esbenp.prettier-vscode)

**Comment by ScottAgirs** [comment]
Hey, @cjboco that's a good point! Would you be interested in submitting a PR for this? If not, no worries, lmk I'll add it! : )

**Comment by ScottAgirs** [comment]
@cjboco after double checking the docs, it actually looks like the ESLint extension step is there (under the VSCode Setup Step). 

As per Prettier, I'm pretty sure you don't need Prettier extension, unless you want to format code outside the scope of JavaScript (so, for example, CSS). 

I'll close this now, but please feel free to re-open if any questions or suggestions.
