### ISSUE TITLE
Error: when using eslint-config-prettier v8.0

### ISSUE THREAD

**Issue by jacargentina** [ijsto/eslint-config#4]
<img width="1206" alt="Captura de Pantalla 2021-04-14 a la(s) 12 27 14" src="https://user-images.githubusercontent.com/517228/114736806-cd10af80-9d1c-11eb-838f-b3abc2265291.png">

**Comment by ScottAgirs** [comment]
@jacargentina some more context would be helpful :)

**Comment by jacargentina** [comment]
@ScottAgirs 

By just looking at the code...

<img width="737" alt="Captura de Pantalla 2021-04-23 a la(s) 21 11 19" src="https://user-images.githubusercontent.com/517228/115940647-b5ea6400-a478-11eb-9de3-9b9f42d1be89.png">

I tried removing 'prettier/react' at line 27. And it worked! No more errors/warnings.

**Comment by ScottAgirs** [comment]
@jacargentina could you please provide the steps you took to @ijsto/eslint-config?

**Comment by jacargentina** [comment]
Steps i took to what ?

**Comment by ScottAgirs** [comment]
When you installed this package, did you use `npx install-peerdeps --dev @ijsto/eslint-config`?

**Comment by jacargentina** [comment]
Yes i did

**Comment by ScottAgirs** [comment]
Okay, thanks, will see if can figure out what caused the errors. If any other details/relevant context comes to mind pls do drop it in here 🙌🏼

**Comment by ScottAgirs** [comment]
Hi @jacargentina this should be addressed with release [v3.0.2](https://github.com/ijsto/eslint-config/releases/tag/v3.0.2). Please update to latest and feel free to reopen, if issue persists.

Thanks for opening the issue.
