### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by valoricDe** [ijsto/eslint-config#8]
Hi @ijsto, I see in my code some errors which might be related to typescript syntax:

<img width="384" alt="Screenshot 2021-06-16 at 17 42 09" src="https://user-images.githubusercontent.com/22564188/122250722-2edec880-ceca-11eb-95ed-6dd69b450dcb.png">

I'm not quite certain because I read that the used babel parser should understand (or rather skip) typescript syntax.
So I'm also not quite sure if it is necessary to introduce the `@typescript-eslint/parser` instead.

I would be willing to work on that but of course only if it is actually needed. 
Do you know more about this topic?

**Comment by ScottAgirs** [comment]
Hey @valoricDe thanks for filing this issue.

I would be happy to take a look at this, however, in the next 1-3 months, sadly, I'm quite swamped with other tasks. If you are keen to take a stab at it, a PR or an issue (as Discussion) would be most welcome, I will try to chime in promptly if submitted.

For now, I am have to say that I would have to read through before I would be able to provide more context.

**Comment by valoricDe** [comment]
Alright thanks for coming back so quickly. I will ask on StackOverflow if someone has some deeper knowledge. Why shall we not the knowledge of the crowd xD

**Comment by ScottAgirs** [comment]
> Alright thanks for coming back so quickly. I will ask on StackOverflow if someone has some deeper knowledge. Why shall we not the knowledge of the crowd xD

Lol, totally! Glhf!

**Comment by ScottAgirs** [comment]
Hey @valoricDe funny how time flies 😅 

Did you ever figure it out? I finally got around to add some instructions for TypeScript projects:

https://github.com/ijsto/eslint-config#typescript

If this still applies to any of your projects, please let me know if this helps.

I'll close for now, if it doesn't work, please let me know too, I'll look into it _**stat**_! :)

**Comment by valoricDe** [comment]
Hey, thanks for the update.
At the end I also switched from babel parser to "parser": "@typescript-eslint/parser" in the project because of the 


    @babel/eslint-parser can't and won't be able to check type issue on TypeScript

    since @typescript-eslint uses TypeScript under the hood, its rules can be made type-aware, which is something Babel doesn't have the ability to do.
